### ISSUE TITLE
ChebYshev’s inequality

### ISSUE THREAD

**Issue by mark-gluzman** [spnbook/spnbook.github.io#1]
**Describe the problem**
Wrong spelling of "Chebyshev" 

**Location**
1. Chapter: 12.8
2. Page: 253
3. Line: #3 from the top

**Proposed solution**
It should be ChebYshev’s inequality, not ChebEshev’s inequality
References: 
1) Wiki: https://en.wikipedia.org/wiki/Chebyshev%27s_inequality
2) page 48 of Chung, Kai Lai (2001). A Course in Probability Theory. Third Edition

**Comment by spnbook** [comment]
Corrected in the online version; is working with CUP, trying to make the correction into the hard copy.

**Comment by spnbook** [comment]
Mark, thanks.

On Oct 25, 2019, at 10:48 AM, Mark Gluzman <notifications@github.com<mailto:notifications@github.com>> wrote:


Describe the bug
Wrong spelling of "Chebyshev"

Location

  1.  Book version: The issue was found on 10/25/19
  2.  Chapter: 12.8
  3.  Page: 253
  4.  Line: #3 from the top

Proposed solution
It should be ChebYshev’s inequality, not ChebEshev’s inequality
References:

  1.  Wiki: https://en.wikipedia.org/wiki/Chebyshev%27s_inequality
  2.  page 48 of Chung, Kai Lai (2001). A Course in Probability Theory. Third Edition
